// ─── GLOBAL CITY DATA (MovAbroad) ─────────────────────────────────────────────

export const GLOBAL_CITIES = [
  { id:'lisbon',    name:'Lisbon',       country:'Portugal',      flag:'🇵🇹', tagline:'Sun-soaked, affordable, English-friendly',        cost:1800, safety:82, healthcare:78, internet:80, expat:88, nightlife:78, nature:70, warmth:88, bestFor:['budget','expats','first-time'], tags:['NHR Tax','D7 Visa','Nomad Visa','Beach','English OK'], stats:{rent:'$972–1,512',meal:'$11–16',cowork:'$162–270',avg_temp:'17°C'}, col:{rent:1150,groceries:280,dining:200,transport:45,cowork:200,utilities:80,leisure:200,health:60}, neighborhoods:['Alfama — historic, hilly, authentic','Príncipe Real — upscale, quiet, boutiques','Mouraria — multicultural, local, rising','Bairro Alto — nightlife, young crowd','Parque das Nações — modern, families'], pros:['Affordable by Western EU standards','Year-round sunshine (300+ days)','Strong English across the city','NHR/IFICI tax benefit for 10 years','Easy beach access'], cons:['Rising rents in city centre','Summer tourist crowds','Bureaucracy slow','D7/Nomad visa processing times'], visa:'Portugal offers the D7 Passive Income Visa ($821/month income) and a Digital Nomad Visa. The NHR/IFICI tax regime offers a flat 20% tax rate for 10 years.' },
  { id:'berlin',   name:'Berlin',       country:'Germany',       flag:'🇩🇪', tagline:'Creative, international, bureaucratic but rewarding', cost:2400, safety:75, healthcare:90, internet:85, expat:85, nightlife:98, nature:65, warmth:45, bestFor:['nightlife','healthcare','tech'], tags:['Freelance Visa','EU base','Tech hub','Arts','English OK'], stats:{rent:'$1,188–2,160',meal:'$13–19',cowork:'$216–378',avg_temp:'10°C'}, col:{rent:1550,groceries:350,dining:280,transport:90,cowork:280,utilities:120,leisure:300,health:80}, neighborhoods:['Mitte — central, expensive, tourist','Prenzlauer Berg — families, cafés, charming','Kreuzberg — multicultural, nightlife','Friedrichshain — young, affordable','Neukölln — diverse, edgy, rising'], pros:['World-class arts & music scene','Large international community','Excellent public healthcare','Freelance visa for non-EU'], cons:['Cold grey winters (Nov–Feb)','Bureaucracy challenging','German increasingly necessary','Rents rising fast'], visa:'Germany offers a Freelancer Visa (Freiberufler) for skilled workers. EU citizens move freely. Non-EU need proven income and qualifications. Processing: 2–5 months.' },
  { id:'chiangmai',name:'Chiang Mai',   country:'Thailand',      flag:'🇹🇭', tagline:'Low cost, warm, legendary nomad base',             cost:1000, safety:78, healthcare:72, internet:82, expat:92, nightlife:68, nature:88, warmth:92, bestFor:['budget','nomads','nature'], tags:['LTR Visa','Nomad hub','Low cost','Buddhist culture','Mountain air'], stats:{rent:'$324–756',meal:'$3–9',cowork:'$65–130',avg_temp:'26°C'}, col:{rent:500,groceries:150,dining:120,transport:30,cowork:90,utilities:50,leisure:120,health:40}, neighborhoods:['Nimman — trendy, cafés, expats','Old City — temples, culture','Santitham — local vibe, affordable','Hang Dong — families, spacious','Mae Rim — nature, villas'], pros:['Extremely low cost of living','Massive nomad community','World-class street food & coffee','Beautiful nature & temples'], cons:['Visa situation complex for long stays','Smoke season Feb–Apr','Language barrier outside tourist areas','Heat and humidity most of year'], visa:'Thailand LTR Visa: 10-year stays for remote workers earning $80k+/yr. Tourist visa extensions and border runs common for shorter stays.' },
  { id:'barcelona',name:'Barcelona',   country:'Spain',         flag:'🇪🇸', tagline:'Architecture, beach, Mediterranean pace',          cost:2200, safety:70, healthcare:85, internet:82, expat:83, nightlife:92, nature:82, warmth:82, bestFor:['lifestyle','beach','culture'], tags:['Nomad Visa','Mediterranean','Startup','Beach','Catalan'], stats:{rent:'$1,080–1,944',meal:'$13–19',cowork:'$194–324',avg_temp:'18°C'}, col:{rent:1400,groceries:310,dining:260,transport:55,cowork:240,utilities:90,leisure:280,health:70}, neighborhoods:['Eixample — elegant, central, walkable','Gràcia — village feel, young, lively','Poblenou — tech hub, beach nearby','El Born — historic lanes, boutiques'], pros:['Mediterranean climate year-round','Beach and mountains same day','Spain Digital Nomad Visa','World-class food & architecture'], cons:['Housing market very competitive','Petty theft in tourist areas','Rents highest in Spain','Overtourism'], visa:"Spain's Digital Nomad Visa: 1 year (renewable to 5). Requires $2,333/month income and non-Spanish employer. Beckham Law: 24% flat tax for first 6 years." },
  { id:'medellin', name:'Medellín',    country:'Colombia',      flag:'🇨🇴', tagline:'Eternal spring, fast-rising tech scene',            cost:1100, safety:62, healthcare:70, internet:78, expat:78, nightlife:88, nature:82, warmth:95, bestFor:['budget','culture','nomads'], tags:['Nomad Visa','Low cost','Spring climate','Vibrant','Tech hub'], stats:{rent:'$432–972',meal:'$4–11',cowork:'$86–162',avg_temp:'22°C'}, col:{rent:650,groceries:170,dining:150,transport:25,cowork:110,utilities:40,leisure:160,health:45}, neighborhoods:['El Poblado — safest, expat hub','Laureles — local feel, good value','Envigado — quieter, residential','Sabaneta — up-and-coming'], pros:['"City of Eternal Spring" 22°C year-round','Very low cost of living','Warm & welcoming culture','Growing tech & nomad scene'], cons:['Safety varies by neighbourhood','Spanish essential','Infrastructure gaps outside El Poblado','Altitude affects some'], visa:'Colombia M-9 Digital Nomad Visa: up to 2 years, requires remote work contract. 90-day tourist entry on arrival for most passports.' },
  { id:'dubai',    name:'Dubai',       country:'UAE',           flag:'🇦🇪', tagline:'Tax-free income, world-class infrastructure',      cost:3200, safety:92, healthcare:85, internet:90, expat:88, nightlife:72, nature:40, warmth:88, bestFor:['safety','tax','business'], tags:['0% tax','Work Visa','World city','Ultra safe','Luxury'], stats:{rent:'$1,620–3,780',meal:'$16–27',cowork:'$270–486',avg_temp:'28°C'}, col:{rent:2500,groceries:450,dining:380,transport:120,cowork:350,utilities:150,leisure:400,health:100}, neighborhoods:['Downtown Dubai — iconic, expensive','Dubai Marina — waterfront, expats','Jumeirah — villas, families, beachside','Business Bay — central, professional'], pros:['Zero income tax','Extremely safe city','World-class infrastructure','Large expat majority (90%)'], cons:['Very expensive','Extreme summer heat (45°C+)','Car-dependent outside centre','Conservative norms'], visa:'UAE Virtual Work Residence Permit: 1-year, $5,000/month min income. Dubai Freelance Permit via Free Zones. Golden Visa for 5–10 year stays.' },
  { id:'tokyo',    name:'Tokyo',       country:'Japan',         flag:'🇯🇵', tagline:'Hyper-efficient, safe, endlessly fascinating',     cost:2600, safety:95, healthcare:90, internet:95, expat:72, nightlife:85, nature:70, warmth:62, bestFor:['safety','internet','culture'], tags:['Startup Visa','Efficient','Unique culture','Ultra-safe','Food'], stats:{rent:'$972–1,944',meal:'$9–16',cowork:'$216–378',avg_temp:'15°C'}, col:{rent:1350,groceries:320,dining:250,transport:100,cowork:275,utilities:110,leisure:280,health:90}, neighborhoods:['Shinjuku — vibrant, everything in one','Shibuya — young, fashion, nightlife','Shimokitazawa — indie, cafés, creative','Nakameguro — trendy, upscale, canal'], pros:['Safest major city in the world',"World's best public transport",'Incredible food culture','Fastest internet in our database'], cons:['Language barrier significant','Visa paths complex','Can feel isolating','Long working-hours culture'], visa:'Japan Digital Nomad Visa (2024): 6 months, ¥10M/yr income. Highly Skilled Professional visa for qualified workers. Startup Visa via Tokyo Metropolitan Government.' },
  { id:'tbilisi',  name:'Tbilisi',     country:'Georgia',       flag:'🇬🇪', tagline:'Hidden gem: 365-day visa-free, ultra-cheap',       cost:900,  safety:80, healthcare:62, internet:78, expat:75, nightlife:82, nature:88, warmth:68, bestFor:['budget','visa','hidden-gem'], tags:['365-day visa-free','0% foreign tax','Ultra low cost','Wine culture','Hidden gem'], stats:{rent:'$324–756',meal:'$4–10',cowork:'$65–130',avg_temp:'13°C'}, col:{rent:500,groceries:140,dining:110,transport:20,cowork:80,utilities:45,leisure:110,health:35}, neighborhoods:['Vake — upscale, expats, green','Old Town / Fabrika — trendy, hipster','Saburtalo — modern, affordable, local','Vera — quiet, charming, central'], pros:['365-day visa-free for 90+ nationalities','Zero tax on foreign-sourced income','Extremely low cost of living','Incredible food, wine & hospitality'], cons:['Healthcare quality limited','Language barrier outside expat areas','Geopolitical uncertainty nearby','Less developed than EU'], visa:'Georgia: 365-day visa-free for citizens of 90+ countries. Foreign income earned abroad is not taxed. Simply arrive and stay — easiest in the world.' },
  { id:'bali',     name:'Bali',        country:'Indonesia',     flag:'🇮🇩', tagline:'Spiritual, tropical, nomad paradise',              cost:1200, safety:72, healthcare:62, internet:72, expat:90, nightlife:82, nature:95, warmth:98, bestFor:['nature','wellness','nomads'], tags:['E33G Visa','Nomad Visa','Tropical','Wellness','Low cost'], stats:{rent:'$432–1,080',meal:'$3–11',cowork:'$86–173',avg_temp:'27°C'}, col:{rent:700,groceries:180,dining:160,transport:35,cowork:120,utilities:60,leisure:180,health:50}, neighborhoods:['Canggu — nomad central, surf, cafés','Ubud — rice fields, culture, wellness','Seminyak — upscale, beach clubs','Sanur — quiet, families, relaxed'], pros:['Stunning natural beauty year-round','Largest nomad community in Asia','Very low cost of living','Warm & sunny year-round'], cons:['Long-term visa path complicated','Traffic in Canggu intense','Healthcare limited','Heavy rains Nov–Mar'], visa:'Indonesia E33G Digital Nomad Visa: 60 days extendable to 180, $2,000/month income. Bali 2nd Home Visa: 10-year stays, $130k deposit.' },
  { id:'prague',   name:'Prague',      country:'Czech Republic',flag:'🇨🇿', tagline:'Central Europe gem, underrated and affordable',    cost:1800, safety:84, healthcare:82, internet:84, expat:76, nightlife:82, nature:72, warmth:55, bestFor:['safety','europe','value'], tags:['EU/Schengen','Freelance visa','Low cost EU','Rich history','Healthcare'], stats:{rent:'$756–1,404',meal:'$9–15',cowork:'$162–270',avg_temp:'10°C'}, col:{rent:1000,groceries:240,dining:190,transport:28,cowork:200,utilities:95,leisure:220,health:55}, neighborhoods:['Vinohrady — elegant, expats, café scene','Žižkov — bohemian, affordable, local','Holešovice — arts district, rising','Dejvice — quiet, upscale, leafy'], pros:['Affordable by Western EU standards','Beautiful historic city centre','EU base in Schengen zone','Good public healthcare'], cons:['Cold winters (Nov–Feb)','Czech language useful','Landlocked, no beach','Limited non-EU residency options'], visa:'EU citizens: free movement. Non-EU: freelance residence permits available. No dedicated digital nomad visa. Processing: 3–6 months.' },
  { id:'athens',   name:'Athens',      country:'Greece',        flag:'🇬🇷', tagline:'Ancient city reborn, affordable EU Mediterranean',  cost:1800, safety:76, healthcare:74, internet:76, expat:76, nightlife:85, nature:80, warmth:86, bestFor:['europe','tax','culture'], tags:['Nomad Visa','EU/Schengen','7% flat tax','Mediterranean','Ancient culture'], stats:{rent:'$756–1,512',meal:'$11–17',cowork:'$151–259',avg_temp:'19°C'}, col:{rent:1050,groceries:260,dining:210,transport:35,cowork:190,utilities:85,leisure:240,health:60}, neighborhoods:['Kolonaki — upscale, embassies, chic','Exarcheia — bohemian, students, alternative','Pangrati — residential, local cafés','Koukaki — up-and-coming, Acropolis views'], pros:['Affordable by EU Mediterranean standards','Greece Nomad Visa + 7% flat tax','Mediterranean climate & food','Incredible history'], cons:['Economic volatility history','Bureaucracy frustrating','Public services inconsistent','Rents rising in central areas'], visa:'Greece Digital Nomad Visa: 1 year renewable, $3,780/month income, 7% flat tax on all foreign income. Available to non-EU remote workers.' },
  { id:'kl',       name:'Kuala Lumpur',country:'Malaysia',      flag:'🇲🇾', tagline:'Modern, multicultural, excellent value in Asia',    cost:1200, safety:75, healthcare:80, internet:82, expat:82, nightlife:72, nature:78, warmth:92, bestFor:['asia','value','healthcare'], tags:['DE Rantau Visa','Low cost','English spoken','Modern city','Food paradise'], stats:{rent:'$432–972',meal:'$3–11',cowork:'$86–173',avg_temp:'28°C'}, col:{rent:650,groceries:160,dining:140,transport:30,cowork:120,utilities:55,leisure:150,health:50}, neighborhoods:['KLCC — central, towers, expensive','Bangsar — expats, cafés, upscale','Mont Kiara — families, international','Bukit Bintang — vibrant, food, shopping'], pros:['Low cost vs quality','English widely spoken','Excellent private healthcare','Diverse food scene'], cons:['Car-dependent outside centre','High humidity & heat year-round','MM2H visa requirements tightened','Air quality during haze season'], visa:'Malaysia DE Rantau Digital Nomad Pass: 3–12 months, RM24,000/year income. 90-day social visit pass on arrival for most nationalities.' },
];

export const GLOBAL_QUESTIONS = [
  { id:'budget',       title:"What's your monthly budget?",    sub:"All in — rent, food, transport, fun.",    multi:false, options:[{icon:'💸',label:'Under $1,100',sub:'Budget mode',value:800},{icon:'💵',label:'$1,100–1,800',sub:'Comfortable frugal',value:1400},{icon:'💳',label:'$1,800–3,000',sub:'Comfortable',value:2400},{icon:'💎',label:'Over $3,000',sub:'No real constraints',value:4000}] },
  { id:'climate',      title:"How important is warm weather?",  sub:"Be honest — some people say they don't care, then hate grey winters.", multi:false, options:[{icon:'☀️',label:'Essential',sub:'Sun is non-negotiable',value:3},{icon:'🌤',label:'Preferred',sub:'Warm helps, not a dealbreaker',value:2},{icon:'🌥',label:'Neutral',sub:'I adapt to any climate',value:1},{icon:'🌨',label:'I like cold',sub:'Give me proper seasons',value:0}] },
  { id:'safety',       title:"How much does safety matter?",    sub:"Everyone wants safe, but tolerance levels differ.", multi:false, options:[{icon:'🛡',label:'Top priority',sub:'Safety above everything',value:3},{icon:'👀',label:'Important',sub:'I want to feel generally safe',value:2},{icon:'🤷',label:"I'll adapt",sub:"I'm street-smart, I manage",value:1},{icon:'🏍',label:'Adventurous',sub:'I embrace some risk',value:0}] },
  { id:'lifestyle',    title:"What's your ideal lifestyle?",    sub:"Pick the one that resonates most deeply.", multi:false, options:[{icon:'🌿',label:'Slow & nature',sub:'Hiking, quiet, green',value:'nature'},{icon:'🌆',label:'Urban & social',sub:'Bars, culture, people',value:'urban'},{icon:'🧘',label:'Wellness',sub:'Yoga, beaches, mindful',value:'wellness'},{icon:'💻',label:'Work-focused',sub:'Coworking, networking',value:'work'}] },
  { id:'priority',     title:"What's your top priority abroad?",sub:"One thing. What matters most of all?", multi:false, options:[{icon:'💰',label:'Save money',sub:'Low cost is key',value:'cost'},{icon:'🌐',label:'Expat community',sub:'Meeting people like me',value:'expat'},{icon:'🏥',label:'Healthcare',sub:'Reliable medical access',value:'health'},{icon:'🧭',label:'Adventure',sub:'New experiences, immersion',value:'culture'}] },
  { id:'deal_breaker', title:"Any deal-breakers?",              sub:"Select anything that would rule a city out.", multi:true, options:[{icon:'❄️',label:'Cold winters',sub:'Below 10°C is a no',value:'cold'},{icon:'🔐',label:'Visa complexity',sub:'I want a clear path',value:'visa'},{icon:'🚨',label:'High crime',sub:'Safety below 70 is a no',value:'crime'},{icon:'💸',label:'High cost',sub:'Over $3,000/mo',value:'expensive'}] },
];

export const BADGE_CFG = {
  budget:       { l:'💰 Best Budget',  c:'#2D7D52' },
  expats:       { l:'👥 Expat Scene',  c:'#1a5c9e' },
  'first-time': { l:'✈️ First-Timer',  c:'#1a5c9e' },
  nomads:       { l:'💻 Nomad Fave',   c:'#C8882A' },
  nature:       { l:'🌿 Nature',       c:'#2D7D52' },
  wellness:     { l:'🧘 Wellness',     c:'#2D7D52' },
  nightlife:    { l:'🎶 Nightlife',    c:'#7A5A9A' },
  healthcare:   { l:'🏥 Healthcare',   c:'#1a5c9e' },
  tech:         { l:'⚡ Tech Hub',     c:'#7A5A9A' },
  lifestyle:    { l:'🌊 Lifestyle',    c:'#C8882A' },
  beach:        { l:'🏖 Beach',        c:'#C8882A' },
  culture:      { l:'🏛 Culture',      c:'#C8882A' },
  safety:       { l:'🛡 Safest',       c:'#1a5c9e' },
  internet:     { l:'⚡ Internet',     c:'#7A5A9A' },
  tax:          { l:'💼 Tax Benefit',  c:'#2D7D52' },
  business:     { l:'🏢 Business',     c:'#7A5A9A' },
  visa:         { l:'🛂 Easy Visa',    c:'#2D7D52' },
  'hidden-gem': { l:'💎 Hidden Gem',   c:'#C8882A' },
  europe:       { l:'🇪🇺 EU Base',     c:'#1a5c9e' },
  value:        { l:'⚖️ Best Value',   c:'#2D7D52' },
  asia:         { l:'🌏 Asia Hub',     c:'#C8882A' },
};

// ─── SCORING ──────────────────────────────────────────────────────────────────
export function scoreCity(city, ans) {
  let s = 0;
  const budget = ans.budget || 2400;
  const diff = city.cost - budget;
  s += diff <= 0 ? 25 : diff <= 300 ? 18 : diff <= 700 ? 8 : 0;
  const cw = ans.climate ?? 1;
  const ws = city.warmth / 100;
  s += cw === 3 ? Math.round(ws*20) : cw === 2 ? Math.round(ws*14+3) : cw === 1 ? 12 : Math.round((1-ws)*15+5);
  const sw = ans.safety ?? 2;
  s += sw === 3 ? Math.round(city.safety/100*20) : sw === 2 ? Math.round(city.safety/100*14+2) : Math.round(city.safety/100*8+6);
  const life = ans.lifestyle;
  s += life==='nature' ? Math.round(city.nature/100*15) : life==='urban' ? Math.round(city.nightlife/100*15) : life==='wellness' ? Math.round((city.nature+city.warmth)/200*15) : life==='work' ? Math.round(city.internet/100*15) : 8;
  const prio = ans.priority;
  s += prio==='cost' ? (budget>=city.cost?15:Math.max(0,15-Math.round((city.cost-budget)/100))) : prio==='expat' ? Math.round(city.expat/100*15) : prio==='health' ? Math.round(city.healthcare/100*15) : prio==='culture' ? Math.round((city.expat+city.nightlife)/200*15) : 8;
  s += Math.round(city.internet/100*5);
  const db = ans.deal_breaker || [];
  if (db.includes('cold') && city.warmth < 50) s -= 25;
  if (db.includes('crime') && city.safety < 70) s -= 25;
  if (db.includes('expensive') && city.cost > 3000) s -= 25;
  return Math.max(0, Math.min(99, s));
}
